project:
  type: book

execute:
  freeze: auto

book:
  title: "interflex -- User Manual"
  sidebar:
    style: docked
    background: light
  chapters:
    - index.qmd
    - intro.qmd
    - classic.qmd
    - lasso.qmd
    - dml.qmd
    - discrete_moderator.qmd
    - discrete_outcome.qmd
    - plot.qmd
    - references.qmd

initial-block:
  language: r
  file: "init.R"

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-fold: false
    code-tools: true
    code-link: true
    toc: true
    toc-depth: 3
    toc-expand: 4

knitr:
  opts_chunk:
    collapse: true
    comment: "#>"

editor: visual
