// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// fastplm
List fastplm(arma::mat data, arma::mat FE, arma::colvec weight, int FEcoefs);
RcppExport SEXP interflex_fastplm(SEXP dataSEXP, SEXP FESEXP, SEXP weightSEXP, SEXP FEcoefsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type data(dataSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type FE(FESEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type weight(weightSEXP);
    Rcpp::traits::input_parameter< int >::type FEcoefs(FEcoefsSEXP);
    rcpp_result_gen = Rcpp::wrap(fastplm(data, FE, weight, FEcoefs));
    return rcpp_result_gen;
END_RCPP
}
// fastplm_predict
arma::colvec fastplm_predict(double mu, arma::mat FEvalues, arma::mat FE, arma::mat newx, arma::mat beta);
RcppExport SEXP interflex_fastplm_predict(SEXP muSEXP, SEXP FEvaluesSEXP, SEXP FESEXP, SEXP newxSEXP, SEXP betaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type FEvalues(FEvaluesSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type FE(FESEXP);
    Rcpp::traits::input_parameter< arma::mat >::type newx(newxSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type beta(betaSEXP);
    rcpp_result_gen = Rcpp::wrap(fastplm_predict(mu, FEvalues, FE, newx, beta));
    return rcpp_result_gen;
END_RCPP
}
